### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by maghidini** [jsreport/jsreport-phantom-image#5]
Using a node app, in Mac OS, already added `phantom-image.phantomPath` on `jsreport.config.json`. 
Both strategies, dedicated-process and phantom-server, gives me an Error: spawn EACCES on phantom-html-to-pdf doing `childProcess.execFile`

**Comment by bjrmatos** [comment]
can you please follow the steps described [here](https://github.com/jsreport/jsreport-phantom-image/issues/3#issuecomment-370054642)? (you need to add some config in phantom-image in order to use it with phantom2)

**Comment by maghidini** [comment]
yes sure, I already set `"phantomPath": "/Users/maghidini/project/node_modules/phantomjs-exact-2-1-1"` . Which is working fine for `phantom-pdf` but not for `phantom-image`. I also ran with my node app with `sudo` and did `chmod 777` to the whole project. No luck so far.

Also, `./node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs --version` gives me 2.1.1

**Comment by bjrmatos** [comment]
can you show the whole configuration content that you are using?

**Comment by maghidini** [comment]
yes sir!, 
`{
  "certificate": {
    "key": "certificates/jsreport.net.key",
    "cert": "certificates/jsreport.net.cert"
  },
  "authentication": {
    "cookieSession": {
      "secret": "<your strong secret>"
    },
    "admin": {
      "username": "admin",
      "password": "password"
    },
    "enabled": false
  },
  "connectionString": {
    "name": "fs"
  },
  "httpPort": 5488,
  "httpsPort": null,
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "blobStorage": "fileSystem",
  "phantom": {
    "strategy": "dedicated-process",
    "timeout": 60000,
    "defaultPhantomjsVersion": "2.1.1"
  },
  "phantom-image": {
    "enabled": true,
    "strategy": "dedicated-process",
    "phantomPath": "/Users/cologhidini/work/bnc-project771/800/node_modules/phantomjs-exact-2-1-1"
  },
  "express": {
    "enabled": false
  },
  "data": {
    "enabled": false
  },
  "tasks": {
    "strategy": "dedicated-process",
    "timeout": 10000,
    "allowedModules": []
  },
  "scripts": {
    "allowedModules": [],
    "timeout": 60000
  },
  "sample-template": {
    "createSamples": true
  }
}`

**Comment by bjrmatos** [comment]
formatted config file:

```js
{
  "certificate": {
    "key": "certificates/jsreport.net.key",
    "cert": "certificates/jsreport.net.cert"
  },
  "authentication": {
    "cookieSession": {
      "secret": "<your strong secret>"
    },
    "admin": {
      "username": "admin",
      "password": "password"
    },
    "enabled": false
  },
  "connectionString": {
    "name": "fs"
  },
  "httpPort": 5488,
  "httpsPort": null,
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "blobStorage": "fileSystem",
  "phantom": {
    "strategy": "dedicated-process",
    "timeout": 60000,
    "defaultPhantomjsVersion": "2.1.1"
  },
  "phantom-image": {
    "enabled": true,
    "strategy": "dedicated-process",
    "phantomPath": "/Users/cologhidini/work/bnc-project771/800/node_modules/phantomjs-exact-2-1-1"
  },
  "express": {
    "enabled": false
  },
  "data": {
    "enabled": false
  },
  "tasks": {
    "strategy": "dedicated-process",
    "timeout": 10000,
    "allowedModules": []
  },
  "scripts": {
    "allowedModules": [],
    "timeout": 60000
  },
  "sample-template": {
    "createSamples": true
  }
}
```

`phantomPath` should be an absolute path to the real phantom executable

please change this: 

```js
"phantom-image": {
    "enabled": true,
    "strategy": "dedicated-process",
    "phantomPath": "/Users/cologhidini/work/bnc-project771/800/node_modules/phantomjs-exact-2-1-1"
  }
```

to this: 

```js
"phantom-image": {
    "enabled": true,
    "strategy": "dedicated-process",
    "phantomPath": "/Users/cologhidini/work/bnc-project771/800/node_modules/phantomjs-exact-2-1-1/lib/phantom/bin/phantomjs"
  }
```

if that does not work, then you mentioned that previous npm install told you that `phantomjs` was found at global cli at `/usr/local/bin/phantomjs`, can yoy try that path too (assuming that it still exits on your machine)? the issue here is that you need to provide the full path to the **real** phantomjs executable. 

for example this path `/Users/cologhidini/work/bnc-project771/800/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs` is not the real phantomjs executable if you look the content you will see that it is a node.js cli wrapper for the real executable, in most cases the real executable is available at `/Users/cologhidini/work/bnc-project771/800/node_modules/phantomjs-exact-2-1-1/lib/phantom/bin/phantomjs` but there could be cases when this is not true, for example when having a global cli installation of phantomjs on your machine.

**Comment by maghidini** [comment]
it worked!!! I set it up to `/usr/local/Cellar/phantomjs/2.1.1/bin/phantomjs` cause I installed with `brew` , thank u so much :)
PD: @bjrmatos sos lo mejor que me paso en el dia jajaja

**Comment by bjrmatos** [comment]
haha de nada, suerte!
